2024-10-24 20:48:10,802 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 20:48:10,808 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 20:48:10,808 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 20:50:20,883 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 20:50:20,890 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 20:50:20,890 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 20:52:39,842 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 20:52:39,847 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 20:52:39,847 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 20:57:20,065 - info_service.utils.logger_utils - INFO - 获取githubRank请求已收到
2024-10-24 20:57:20,065 - info_service.utils.logger_utils - INFO - 开始获取GitHub排名信息
2024-10-24 20:57:20,066 - info_service.utils.logger_utils - INFO - 成功获取GitHub排名信息: {'rank': 1, 'info': 'example_info'}
2024-10-24 20:57:20,066 - info_service.utils.logger_utils - INFO - 获取githubRank请求处理完毕
2024-10-24 20:57:20,066 - app - ERROR - Exception on /info/rank [GET]
Traceback (most recent call last):
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\info_service\routes\info_routes.py", line 20, in rank
    return jsonify(response[0]), response[1]
                   ~~~~~~~~^^^
KeyError: 0
2024-10-24 20:57:20,069 - werkzeug - INFO - 127.0.0.1 - - [24/Oct/2024 20:57:20] "[35m[1mGET /info/rank HTTP/1.1[0m" 500 -
2024-10-24 20:57:32,492 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 20:57:32,500 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 20:57:32,500 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 20:57:41,882 - info_service.utils.logger_utils - INFO - 获取githubRank请求已收到
2024-10-24 20:57:41,882 - info_service.utils.logger_utils - INFO - 开始获取GitHub排名信息
2024-10-24 20:57:41,883 - info_service.utils.logger_utils - INFO - 成功获取GitHub排名信息: {'rank': 1, 'info': 'example_info'}
2024-10-24 20:57:41,883 - info_service.utils.logger_utils - INFO - 获取githubRank请求处理完毕
2024-10-24 20:57:41,883 - app - ERROR - Exception on /info/rank [GET]
Traceback (most recent call last):
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\info_service\routes\info_routes.py", line 20, in rank
    return jsonify(response[0]), response[1]
                   ~~~~~~~~^^^
KeyError: 0
2024-10-24 20:57:41,885 - werkzeug - INFO - 127.0.0.1 - - [24/Oct/2024 20:57:41] "[35m[1mGET /info/rank HTTP/1.1[0m" 500 -
2024-10-24 21:01:18,886 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 21:01:18,895 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 21:01:18,895 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 21:01:32,901 - info_service.utils.logger_utils - INFO - 获取githubRank请求已收到
2024-10-24 21:01:32,902 - info_service.utils.logger_utils - INFO - 开始获取GitHub排名信息
2024-10-24 21:01:32,902 - info_service.utils.logger_utils - INFO - 成功获取GitHub排名信息: None
2024-10-24 21:01:32,902 - info_service.utils.logger_utils - INFO - 获取githubRank请求处理完毕
2024-10-24 21:01:32,903 - app - ERROR - Exception on /info/rank [GET]
Traceback (most recent call last):
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\info_service\routes\info_routes.py", line 20, in rank
    return jsonify(response[0]), response[1]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\yj998\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
2024-10-24 21:01:32,906 - werkzeug - INFO - 127.0.0.1 - - [24/Oct/2024 21:01:32] "[35m[1mGET /info/rank HTTP/1.1[0m" 500 -
2024-10-24 21:03:56,396 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 21:03:56,406 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 21:03:56,406 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 21:04:02,139 - info_service.utils.logger_utils - INFO - 获取githubRank请求已收到
2024-10-24 21:04:02,139 - info_service.utils.logger_utils - INFO - 开始获取GitHub排名信息
2024-10-24 21:04:02,139 - info_service.utils.logger_utils - INFO - 成功获取GitHub排名信息: {}
2024-10-24 21:04:02,139 - info_service.utils.logger_utils - INFO - 获取githubRank请求处理完毕
2024-10-24 21:04:02,139 - app - ERROR - Exception on /info/rank [GET]
Traceback (most recent call last):
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\info_service\routes\info_routes.py", line 20, in rank
    return jsonify(response[0]), response[1]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\yj998\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\yj998\python_project\to-github\.venv\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable
2024-10-24 21:04:02,141 - werkzeug - INFO - 127.0.0.1 - - [24/Oct/2024 21:04:02] "[35m[1mGET /info/rank HTTP/1.1[0m" 500 -
2024-10-24 21:06:09,824 - user_service.utils.logger_utils - INFO - Flask 应用已创建并配置完成
2024-10-24 21:06:09,829 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5002
2024-10-24 21:06:09,830 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2024-10-24 21:06:17,130 - info_service.utils.logger_utils - INFO - 获取githubRank请求已收到
2024-10-24 21:06:17,130 - info_service.utils.logger_utils - INFO - 开始获取GitHub排名信息
2024-10-24 21:06:17,130 - info_service.utils.logger_utils - INFO - 成功获取GitHub排名信息: {}
2024-10-24 21:06:17,130 - info_service.utils.logger_utils - INFO - 获取githubRank请求处理完毕
2024-10-24 21:06:17,131 - werkzeug - INFO - 127.0.0.1 - - [24/Oct/2024 21:06:17] "GET /info/rank HTTP/1.1" 200 -
